unrestricted_licenses:
  - Apache-2.0
  - CC-BY-3.0
  - ISC
  - AFL-2.1
  - AFL-3.0
  - Artistic-1.0
  - Artistic-2.0
  - Apache-1.1
  - BSD-1-Clause
  - BSD-2-Clause
  - BSD-3-Clause
  - 0BSD
  - FTL
  - LPL-1.02
  - MS-PL
  - MIT
  - NCSA
  - OpenSSL
  - PHP-3.0
  - TCP-wrappers
  - W3C
  - Xnet
  - Zlib

reciprocal_licenses:
  - CC0-1.0
  - APSL-2.0
  - CDDL-1.0
  - CDDL-1.1
  - CPL-1.0
  - EPL-1.0
  - IPL-1.0
  - MPL-1.0
  - MPL-1.1
  - MPL-2.0
  - MPL-2.0-no-copyleft-exception
  - Ruby

restricted_licenses:
  - GPL-1.0-only
  - GPL-1.0-or-later
  - GPL-2.0-only
  - GPL-2.0-or-later
  - GPL-3.0-only
  - GPL-3.0-or-later
  - LGPL-2.0-only
  - LGPL-2.0-or-later
  - LGPL-2.1-only
  - LGPL-2.1-or-later
  - LGPL-3.0-only
  - LGPL-3.0-or-later
  - NPL-1.0
  - NPL-1.1
  - OSL-1.0
  - OSL-1.1
  - OSL-2.0
  - OSL-2.1
  - OSL-3.0
  - QPL-1.0
  - Sleepycat

allowlisted_modules:
  # MIT license in README
  - github.com/kr/logfmt

  # https://github.com/xeipuuv/gojsonpointer/blob/master/LICENSE-APACHE-2.0.txt
  - github.com/xeipuuv/gojsonpointer

  # https://github.com/xeipuuv/gojsonreference/blob/master/LICENSE-APACHE-2.0.txt
  - github.com/xeipuuv/gojsonreference

  # Apache 2.0: https://github.com/xeipuuv/gojsonschema/blob/master/LICENSE-APACHE-2.0.txt
  - github.com/xeipuuv/gojsonschema

  # MIT: https://github.com/bgentry/speakeasy/blob/master/LICENSE
  - github.com/bgentry/speakeasy

  # BSD: https://github.com/BurntSushi/xgb/blob/master/LICENSE
  - github.com/BurntSushi/xgb

  # BSD: https://github.com/DATA-DOG/go-sqlmock/blob/master/LICENSE
  - github.com/DATA-DOG/go-sqlmock

  # MIT: https://github.com/ghodss/yaml/blob/master/LICENSE
  - github.com/ghodss/yaml

  # BSD: https://github.com/gogo/protobuf/blob/master/LICENSE
  - github.com/gogo/protobuf

  # Apache 2: https://github.com/google/pprof/blob/master/LICENSE
  - github.com/google/pprof

  # BSD: https://github.com/magiconair/properties/blob/master/LICENSE.md
  - github.com/magiconair/properties

  # Apache 2: https://github.com/opencontainers/runc/blob/master/LICENSE
  - github.com/opencontainers/runc

  # BSD: https://github.com/rcrowley/go-metrics/blob/master/LICENSE
  - github.com/rcrowley/go-metrics
  - github.com/yvasiyarov/go-metrics # fork of above with identical license

  # Public domain: https://github.com/xi2/xz/blob/master/LICENSE
  - github.com/xi2/xz

  # BSD-3
  #   fuse.go: ISC
  #   fuse_kernel.go: BSD-2
  - bazil.org/fuse

  # BSD-3
  - github.com/DataDog/zstd

  # BSD-2 / ISC
  - github.com/emirpasic/gods

  # MIT / MIT
  - github.com/kevinburke/ssh_config

  # Apache 2.0
  #   github.com/ghodss/yaml: MIT / BSD-3
  #   github.com/gogo/protobuf: BSD-3
  #   github.com/jmespath/go-jmespath: Apache 2.0
  #   sigs.k8s.io/yaml: MIT / BSD-3
  - github.com/tektoncd/pipeline

  # The core library is MIT licensed, but a submodule imports a BSD-3 license that licensee fails to correctly identify
  - github.com/vektah/gqlparser

  # Apache 2.0
  - github.com/spf13/cobra
  - github.com/spf13/afero

  # BSD-3 by pointer to another repo (github.com/gonum/license/blob/master/LICENSE)
  - gonum.org/v1/plot

  # FTL (https://github.com/golang/freetype/blob/master/licenses/ftl.txt)
  - github.com/golang/freetype

  # CC-BY-3
  - github.com/ajstarks/svgo

  # MIT
  - github.com/dgryski/go-metro
  - github.com/hhatto/gorst

  # Apache 2.0 (but missing appendix): https://github.com/garyburd/redigo/blob/master/LICENSE
  - github.com/garyburd/redigo
  - github.com/gomodule/redigo

  # Apache 2.0: https://github.com/xdg/scram/blob/master/LICENSE
  - github.com/xdg/scram

  # Apache 2.0: https://github.com/xdg/stringprep/blob/master/LICENSE
  - github.com/xdg/stringprep

  # Helm is Apache 2.0: https://github.com/helm/helm/blob/master/LICENSE
  # However, it has a bunch of LICENSE test files that our linter fails to understand
  - k8s.io/helm
  - helm.sh/helm/v3

  # MIT: https://github.com/kubernetes-sigs/yaml/blob/master/LICENSE
  - sigs.k8s.io/yaml

  - k8s.io/kubernetes
  - modernc.org/cc
  - github.com/smartystreets/assertions
  - github.com/smartystreets/goconvey
  - github.com/bmizerany/assert

